import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';

/// Firebase service for analytics and push notifications
class FirebaseService {
  static final FirebaseService _instance = FirebaseService._internal();
  factory FirebaseService() => _instance;
  FirebaseService._internal();

  static FirebaseService get instance => _instance;

  FirebaseAnalytics? _analytics;
  FirebaseMessaging? _messaging;

  FirebaseAnalytics? get analytics => _analytics;
  FirebaseMessaging? get messaging => _messaging;

  /// Initialize Firebase services
  /// Note: Requires firebase_options.dart generated by FlutterFire CLI
  Future<void> initialize() async {
    try {
      // Initialize Firebase
      // TODO: Run `flutterfire configure` to generate firebase_options.dart
      // await Firebase.initializeApp(
      //   options: DefaultFirebaseOptions.currentPlatform,
      // );

      // For now, we'll skip Firebase initialization until configured
      // This allows the app to run without Firebase setup
      debugPrint('⚠️ Firebase not configured yet');
      debugPrint('💡 Run: flutterfire configure');
      debugPrint('💡 Then uncomment Firebase.initializeApp() in firebase_service.dart');

      return;

      // Uncomment below after running `flutterfire configure`
      /*
      _analytics = FirebaseAnalytics.instance;
      _messaging = FirebaseMessaging.instance;

      // Configure Analytics
      await _analytics?.setAnalyticsCollectionEnabled(true);

      if (kDebugMode) {
        debugPrint('✅ Firebase Analytics initialized');
      }

      // Request notification permissions
      NotificationSettings settings = await _messaging!.requestPermission(
        alert: true,
        announcement: false,
        badge: true,
        carPlay: false,
        criticalAlert: false,
        provisional: false,
        sound: true,
      );

      if (kDebugMode) {
        debugPrint('📱 Notification permission: ${settings.authorizationStatus}');
      }

      // Get FCM token
      String? token = await _messaging?.getToken();
      if (kDebugMode) {
        debugPrint('🔑 FCM Token: $token');
      }

      // Listen to foreground messages
      FirebaseMessaging.onMessage.listen(_handleForegroundMessage);

      // Handle background messages
      FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

      if (kDebugMode) {
        debugPrint('✅ Firebase Messaging initialized');
      }
      */
    } catch (e) {
      if (kDebugMode) {
        debugPrint('❌ Firebase initialization error: $e');
      }
    }
  }

  // Uncomment when Firebase is configured
  /*
  /// Handle foreground messages
  void _handleForegroundMessage(RemoteMessage message) {
    if (kDebugMode) {
      debugPrint('📨 Foreground message: ${message.notification?.title}');
    }

    // TODO: Show local notification or in-app alert
    // You can use flutter_local_notifications here
  }
  */

  /// Log analytics event
  Future<void> logEvent({
    required String name,
    Map<String, Object>? parameters,
  }) async {
    try {
      await _analytics?.logEvent(
        name: name,
        parameters: parameters,
      );

      if (kDebugMode) {
        debugPrint('📊 Analytics event: $name ${parameters ?? ""}');
      }
    } catch (e) {
      if (kDebugMode) {
        debugPrint('❌ Analytics error: $e');
      }
    }
  }

  /// Log screen view
  Future<void> logScreenView({
    required String screenName,
    String? screenClass,
  }) async {
    try {
      await _analytics?.logScreenView(
        screenName: screenName,
        screenClass: screenClass ?? screenName,
      );

      if (kDebugMode) {
        debugPrint('📱 Screen view: $screenName');
      }
    } catch (e) {
      if (kDebugMode) {
        debugPrint('❌ Screen view error: $e');
      }
    }
  }

  /// Set user properties
  Future<void> setUserProperty({
    required String name,
    required String value,
  }) async {
    try {
      await _analytics?.setUserProperty(
        name: name,
        value: value,
      );

      if (kDebugMode) {
        debugPrint('👤 User property: $name = $value');
      }
    } catch (e) {
      if (kDebugMode) {
        debugPrint('❌ User property error: $e');
      }
    }
  }

  /// Set user ID
  Future<void> setUserId(String? userId) async {
    try {
      await _analytics?.setUserId(id: userId);

      if (kDebugMode) {
        debugPrint('👤 User ID set: $userId');
      }
    } catch (e) {
      if (kDebugMode) {
        debugPrint('❌ Set user ID error: $e');
      }
    }
  }
}

/// Background message handler (must be top-level function)
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // await Firebase.initializeApp();

  if (kDebugMode) {
    debugPrint('📨 Background message: ${message.notification?.title}');
  }

  // TODO: Handle background message
}
